### ISSUE TITLE
Center data and scale to standard

### ISSUE THREAD

**Issue by aleximmer** [GlooperLabs/GraphTime#10]
Prior to fitting the dynamic graphical model, the data has to be centered. How does scaling affect the performance, should we ensure unit variance? It seems that magnitude could affect the l2 regularisation.

**Comment by AlexGibberd** [comment]
Scaling would generally mean that different regularisers would be required to obtain the same effect , i.e. to obtain similar changepoint/graph patterns. I think a larger variance will require more regularisation in general. 

In order to maintain reasonable default ranges for parameter sweeps, it would be best to try and ensure unit variance (when measured across the full dataset). The geninv function (MATLAB) is set up to ensure the diagonal of the covariance matrices is equal to one.

**Comment by aleximmer** [comment]
Okay, so I will add a scaler and centering as options for a dynamic graphical model.

**Comment by AlexGibberd** [comment]
Yes, that would be a worthwhile addition. We can also rescale the solution after the algorithm has run. For example, store the re-scaling parameters at the start, and then perform the inverse scaling operation on the solution.

**Comment by aleximmer** [comment]
That would mean, we have to rescale the resulting covariance matrix and then invert it again. Is there anything else that has to be done to ensure proper functionality when scaling in the beginning and rescaling in the end? 

Especially, how does it relate to Theta and sparse_Theta?

**Comment by AlexGibberd** [comment]
There are two problems here, however, solutions may share components:

**removing mean structure (i.e. a trend):**
This can be dealt with in various ways, typically methods for the regularised graph estimation assume mean zero. As you point out, it is worthwhile including some functions for this in the package. I suggest:

1. Simple empirical mean, assume the mean is constant across all data, estimate and subtract
2. Moving window empirical mean, assume that mean is approximately constant in a window of limited size. Estimate the mean locally in the window and subtract at the point the window is centered at. User should specify window width and any related weighting function (if not uniform)
3. Wavelet denoising, see Donoho1994. This provides a fairly hands-free way to estimate trends. The specifics of its effectiveness will depend on factors like wavelet choice. (see classic paper: http://www.stat.ucla.edu/~cocteau/stat204/readings/spatialadapt.pdf)
4. Trend filtering, closely related to wavelet denoising (extremely related to GFGL/IFGL). Effectively estimates trends with a penalised regularisation approach. User options would be the degree of trend, i.e. piecewise linear, polynomial, and the strength of the regulariser (see https://arxiv.org/abs/1304.2986)

**Scaling the covariance/precision**

This relates to the idea that the scale of the covariance (or marginal variance) may require adjustments to the regularisation strength..a larger variance may require larger regularisation. To avoid this extra degree of freedom, one may choose to instead model the correlation and inverse correlation matrices (effectively covariance normalised to one). However, again, as with the mean estimation, we are required to map from the data to a setting where the marginal variance is approximately one (this should be true across the whole series).

The process would roughly follow:
1 - rescale data such that marginal variance appears to be constant (value one)
2 - Apply regularised graph estimation to resultant correlation matrix
3 - Rescale estimate precision matrix such that it represents partial-correlation (diag of precision=1)
3 - (optional) rescale the regularised partial correlation matrix (3) to the original scale

For actually estimating the marginal variance (in order to rescale the empirical covariance), we could use:
- Options 1 and 2 (i.e. constant and moving window estimation) in the mean/trend removal setting equally apply to estimation of trends in the scale of the covariance. 
- Adapt the wavelet denoising scheme (Option 3) to estimate marginal variances of the data streams. From this, we can rescale the empirical covariance to that which has a roughly unit variance. 
- Finally, Option 4 is essentially applying IFGL/GFGL to the raw data.
